kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: glusterfs-simple
  namespace: gfs
provisioner: gluster.org/glusterfs-simple
parameters:
  forceCreate: "true"
  brickrootPaths: "192.168.12.187:/gfs-brick,192.168.12.189:/gfs-brick,192.168.12.199:/gfs-brick"
  volumeType: "replica 3"
